name: Build WebKit on Windows

on:
  workflow_dispatch:
    inputs:
      webkit_hash:
        description: 'Commit hash of WebKit/WebKit to build'
        required: true 
        default: 'main'

jobs:
  build:
    runs-on: windows-2022
    env:
      WEBKIT_INSTALL_DIR: ${{ github.workspace }}\webkit-install
      WEBKIT_HEADERS_DIR: ${{ github.workspace }}\webkit-install\webkit-headers
      VCPKG_ROOT: 'C:\Program Files\vcpkg'
   
    steps:
    - name: Install Windows requirements
      run: |
        choco install -y gperf ninja
        python -m pip install pywin32
        
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true 
    - uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.31'
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: "5.32"
        distribution: strawberry
        
    - name: Enable long paths in Windows
      run: |
        Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1
        git config --global core.longpaths true

    - name: Restore WebKit checkout from cache
      uses: actions/cache@v3
      with:
        path: WebKit
        key: webkit-${{ github.event.inputs.webkit_hash }}
        
    - name: Checkout Webkit at hash
      if: steps.cache-webkit.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: 'WebKit/WebKit'
        ref: ${{ github.event.inputs.webkit_hash }}
        path: WebKit
        
    - name: Save WebKit checkout to cache
      if: steps.cache-webkit.outputs.cache-hit != 'true'
      uses: actions/cache@v3
      with:
        path: WebKit
        key: webkit-${{ github.event.inputs.webkit_hash }}
        
    - name: Set environment variables for build
      shell: cmd
      working-directory: WebKit
      run: |
        set "PATH=%ProgramFiles%\CMake\bin;%PATH%"
        set "PATH=%ProgramFiles(x86)%\Microsoft Visual Studio\Installer;%PATH%"
        for /F "usebackq delims=" %%I in (`vswhere.exe -latest -property installationPath`) do set VSPATH=%%I
        set "PATH=%~dp0WebKitLibraries\win\bin;%PATH%"
        set "WEBKIT_TESTFONTS=%~dp0Tools\WebKitTestRunner\fonts"
        set "DUMPRENDERTREE_TEMP=%TEMP%"
        set "CC=clang-cl"
        set "CXX=clang-cl"
        echo %PATH%
        echo WEBKIT_TESTFONTS=%WEBKIT_TESTFONTS%
        echo DUMPRENDERTREE_TEMP=%DUMPRENDERTREE_TEMP%
        echo CC=%CC%
        echo CXX=%CXX%
        echo VSPATH=%VSPATH%
        call "%VSPATH%\VC\Auxiliary\Build\vcvars64.bat"

    - name: Build WebKit
      working-directory: WebKit
      run: |
        & perl .\Tools\Scripts\build-webkit --release --platform=win --prefix="${{ env.WEBKIT_INSTALL_DIR }}"

    - name: Post-build:Install and Copy Headers
      shell: bash
      working-directory: WebKit/Release
      run: |
        cmake --install 
        mkdir -p "${{ env.WEBKIT_HEADERS_DIR }}"
        for dir in */; do
          if [ ! -d "$dir/Headers" ]; then
            continue
          fi
          cp -r "$dir/Headers/"* "${{ env.WEBKIT_HEADERS_DIR }}"
        done

    - name: Compress install folder for download
      run: |
        Compress-Archive -Path "${{ env.WEBKIT_INSTALL_DIR }}" -DestinationPath "${{ env.WEBKIT_INSTALL_DIR }}.zip"

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: webkit-windows-build
        path: ${{ env.WEBKIT_INSTALL_DIR }}.zip
